[project]
name = "pipelines"
version = "0.1.0"
description = ""
authors = [
    { name="Toby Drane" }
]
readme = "README.md"
dependencies = [
    "pulumi",
    "pulumi-aws",
    "dagster",
    "dagit"
]

[tool.setuptools]
py-modules = []

[tool.dagster]
module_name = "pipelines"